# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""Error

    Error(;
        code=nothing,
        message=nothing,
    )

    - code::Int64 : The server error code returned
    - message::String : The error message generated by the server
"""
Base.@kwdef mutable struct Error <: OpenAPI.APIModel
    code::Union{Nothing, Int64} = nothing
    message::Union{Nothing, String} = nothing

    function Error(code, message, )
        OpenAPI.validate_property(Error, Symbol("code"), code)
        OpenAPI.validate_property(Error, Symbol("message"), message)
        return new(code, message, )
    end
end # type Error

const _property_types_Error = Dict{Symbol,String}(Symbol("code")=>"Int64", Symbol("message")=>"String", )
OpenAPI.property_type(::Type{ Error }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_Error[name]))}

function check_required(o::Error)
    true
end

function OpenAPI.validate_property(::Type{ Error }, name::Symbol, val)
end
