# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""License

    License(;
        name=nothing,
    )

    - name::String : Name of the license
"""
Base.@kwdef mutable struct License <: OpenAPI.APIModel
    name::Union{Nothing, String} = nothing

    function License(name, )
        OpenAPI.validate_property(License, Symbol("name"), name)
        return new(name, )
    end
end # type License

const _property_types_License = Dict{Symbol,String}(Symbol("name")=>"String", )
OpenAPI.property_type(::Type{ License }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_License[name]))}

function check_required(o::License)
    o.name === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ License }, name::Symbol, val)
    if name === Symbol("name")
        OpenAPI.validate_param(name, "License", :enum, val, ["CC0-1.0", "CC-BY-SA-4.0", "GPL-2.0", "ODbL-1.0", "CC-BY-NC-SA-4.0", "unknown", "DbCL-1.0", "CC-BY-SA-3.0", "copyright-authors", "other", "reddit-api", "world-bank", "CC-BY-4.0", "CC-BY-NC-4.0", "PDDL", "CC-BY-3.0", "CC-BY-3.0-IGO", "US-Government-Works", "CC-BY-NC-SA-3.0-IGO", "CDLA-Permissive-1.0", "CDLA-Sharing-1.0", "CC-BY-ND-4.0", "CC-BY-NC-ND-4.0", "ODC-BY-1.0", "LGPL-3.0", "AGPL-3.0", "FDL-1.3", "EU-ODP-Legal-Notice", "apache-2.0"])
    end
end
