# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""ModelInstanceNewVersionRequest

    ModelInstanceNewVersionRequest(;
        versionNotes=nothing,
        files=nothing,
    )

    - versionNotes::String : The version notes for the model instance version
    - files::Vector{UploadFile} : A list of files that should be associated with the model instance version
"""
Base.@kwdef mutable struct ModelInstanceNewVersionRequest <: OpenAPI.APIModel
    versionNotes::Union{Nothing, String} = nothing
    files::Union{Nothing, Vector} = nothing # spec type: Union{ Nothing, Vector{UploadFile} }

    function ModelInstanceNewVersionRequest(versionNotes, files, )
        OpenAPI.validate_property(ModelInstanceNewVersionRequest, Symbol("versionNotes"), versionNotes)
        OpenAPI.validate_property(ModelInstanceNewVersionRequest, Symbol("files"), files)
        return new(versionNotes, files, )
    end
end # type ModelInstanceNewVersionRequest

const _property_types_ModelInstanceNewVersionRequest = Dict{Symbol,String}(Symbol("versionNotes")=>"String", Symbol("files")=>"Vector{UploadFile}", )
OpenAPI.property_type(::Type{ ModelInstanceNewVersionRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_ModelInstanceNewVersionRequest[name]))}

function check_required(o::ModelInstanceNewVersionRequest)
    o.files === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ ModelInstanceNewVersionRequest }, name::Symbol, val)
end
