# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.


@doc raw"""CreateInboxFileRequest

    CreateInboxFileRequest(;
        virtualDirectory=nothing,
        blobFileToken=nothing,
    )

    - virtualDirectory::String : Directory name used for tagging the uploaded file
    - blobFileToken::String : Token representing the uploaded file
"""
Base.@kwdef mutable struct CreateInboxFileRequest <: OpenAPI.APIModel
    virtualDirectory::Union{Nothing, String} = nothing
    blobFileToken::Union{Nothing, String} = nothing

    function CreateInboxFileRequest(virtualDirectory, blobFileToken, )
        OpenAPI.validate_property(CreateInboxFileRequest, Symbol("virtualDirectory"), virtualDirectory)
        OpenAPI.validate_property(CreateInboxFileRequest, Symbol("blobFileToken"), blobFileToken)
        return new(virtualDirectory, blobFileToken, )
    end
end # type CreateInboxFileRequest

const _property_types_CreateInboxFileRequest = Dict{Symbol,String}(Symbol("virtualDirectory")=>"String", Symbol("blobFileToken")=>"String", )
OpenAPI.property_type(::Type{ CreateInboxFileRequest }, name::Symbol) = Union{Nothing,eval(Base.Meta.parse(_property_types_CreateInboxFileRequest[name]))}

function check_required(o::CreateInboxFileRequest)
    o.virtualDirectory === nothing && (return false)
    o.blobFileToken === nothing && (return false)
    true
end

function OpenAPI.validate_property(::Type{ CreateInboxFileRequest }, name::Symbol, val)
end
