# This file was generated by the Julia OpenAPI Code Generator
# Do not modify this file directly. Modify the OpenAPI specification instead.

module APIClient

using Dates, TimeZones
using OpenAPI
using OpenAPI.Clients

const API_VERSION = "1"

include("modelincludes.jl")

include("apis/api_KaggleApi.jl")

end # module APIClient
